mutation CreateAssetMaintenanceEvent($input: CreateAssetMaintenanceEventsInput!) {
  createAssetMaintenanceEvent(input: $input) {
    assetMaintenanceEvent { id asset { id } maintenanceEvent { id } }
  }
}
