mutation UpdateDocumentType($input: UpdateDocumentTypesInput!) {
  updateDocumentType(input: $input) {
    documentType { id name header content footer styles subject incrementPattern incremental dateIssued dateDue }
  }
}
