mutation CreateClient($input: CreateClientsInput!) {
  createClient(input: $input) {
    client {
      id organisationName address1 address2 address3 city county postcode discount
      clientType { id name }
    }
  }
}
