mutation CreateAssetTypeMaintenanceSchedule($input: CreateAssetTypeMaintenanceSchedulesInput!) {
  createAssetTypeMaintenanceSchedule(input: $input) {
    assetTypeMaintenanceSchedule { id assetType { id } maintenanceSchedule { id } }
  }
}
