mutation CreateAssetTypeMultiplierType($input: CreateAssetTypeMultiplierTypesInput!) {
  createAssetTypeMultiplierType(input: $input) {
    assetTypeMultiplierType { id assetType { id } multiplierType { id } }
  }
}
